# Generated by Django 4.2.2 on 2023-06-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_foto_svaz_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='svaz',
            name='data_roj',
            field=models.DateField(auto_now_add=True, verbose_name='Дата рождения'),
        ),
    ]
