# Generated by Django 4.2.2 on 2023-06-16 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_svaz_data_roj'),
    ]

    operations = [
        migrations.AddField(
            model_name='svaz',
            name='otvet',
            field=models.BooleanField(default=False, verbose_name='Ответили'),
        ),
        migrations.AlterField(
            model_name='svaz',
            name='data_roj',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
    ]
